### ISSUE TITLE
Footer not sticking to bottom

### ISSUE THREAD

**Issue by siduck** [developersIndia/saadhan#12]
### What happened?

Footer in the site isn't fixed to the bottom

![Screenshot_20230206_174944](https://user-images.githubusercontent.com/59060246/216969862-64da7eef-53d2-4994-b583-3b77862abf6b.png)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Bhupesh-V** [comment]
Thanks for the report @siduck. Let me know if you want to pick this up.

**Comment by siduck** [comment]
@Bhupesh-V i dont see any CSS used in the site, how do I style the footer?

**Comment by Bhupesh-V** [comment]
> @Bhupesh-V i dont see any CSS used in the site, how do I style the footer?

Seems like @ansid0102 already created a PR #14 , maybe you can help them provide feedback/test/improve the changes.

**Comment by Bhupesh-V** [comment]
@all-contributors please add @siduck  for bug
