### ISSUE TITLE
Empty button in navbar

### ISSUE THREAD

**Issue by rashhocket** [developersIndia/saadhan#16]
### What happened?

There's an empty button in the navbar. Check out the third link in the code below:
```
<div class="navbar-start">
  <a href="/" class="navbar-item">
    Home
  </a>
  <a href="/" class="navbar-item">
    How to contribute
  </a>
  <a href="/" class="navbar-item">
  </a>
  <a href="/contributors" class="navbar-item">
    Contributors
  </a>
  <a href="/" class="navbar-item">
    Wiki
  </a>
</div>
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhupesh-V** [comment]
Would you like to fix it?

**Comment by rashhocket** [comment]
Sure thing! I’ll raise a PR
