### ISSUE TITLE
All resource "Open Link" buttons turn into "Copy Link" buttons and stop working after following steps:

### ISSUE THREAD

**Issue by HarshRaj2717** [developersIndia/saadhan#19]
## Go through the following steps:

1. Go to homepage and click on any topic (Python, Javascript, C++, etc). - Currently you will see many "open link" buttons which working.
2. Change any filter ("filter by level" or "filter by type"). - Now, all the "open link" buttons change into "copy link" buttons which don't work.
3. Change the filters again to go back to original settings. - At first step we saw many "open link" buttons but now they all are "copy link" buttons which don't work.

[Screencast from 2023-02-06 21-12-17.webm](https://user-images.githubusercontent.com/90465144/217020635-1c345c26-e87d-4d28-bbf3-2b6bec69642b.webm)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhupesh-V** [comment]
Thanks for the bug report @HarshRaj2717 

This should be fixed by https://github.com/developersIndia/saadhan/pull/3

**Comment by Bhupesh-V** [comment]
Fixed in #21
