### ISSUE TITLE
Isn't it like reinventing the wheel?

### ISSUE THREAD

**Issue by Abhinav-6** [developersIndia/saadhan#25]
### What happened?

There are lot website already available that have huge list of resource. I don't think there was any need to make this website. Websites like roadmap.sh provide roadmap and resource for almost every career path. Github repo like markodonic/web-development-resource have thousand of resources already listed and have about 1k contributers and 5.5k stars.
Github repo ripienaar/free-for-dev have almost all resources that free for developers, have 7.5k contributers and 66.5k stars.

I think this repo is just redundant or waste of time, that's why people are not contributing in this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhupesh-V** [comment]
Thanks for your concern on determining if something's a waste of time or not. All those resources you mentioned are great and should/can be looked up for learning new things.
