### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/saadhan#4]
### Feature details?

Add meta headers to setup google analytics & search console

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KaviiSuri** [comment]
Can I pick it up?

**Comment by Bhupesh-V** [comment]
> Can I pick it up?

Hey man, this one is assigned to me since it will require access to google accounts. Feel free to pick issues which are "not assigned to anybody"

**Comment by Tintedfireglass** [comment]
Can we not have Google analytics on this website? It feels against the spirit of the internet. Do we really news that analytics? why do we Ned to connect everything to Google?

**Comment by Bhupesh-V** [comment]
> Can we not have Google analytics on this website? It feels against the spirit of the internet. Do we really news that analytics? why do we Ned to connect everything to Google?

I feel ya, but we need it to see how far saadhan can reach. For those who don't like trackers one can always block it.

**Comment by Tintedfireglass** [comment]
> > Can we not have Google analytics on this website? It feels against the spirit of the internet. Do we really news that analytics? why do we Ned to connect everything to Google?
> 
> I feel ya, but we need it to see how far saadhan can reach. For those who don't like trackers one can always block it.

I understand that we need analytics but having a closed source analytics plugin on a FOSS Community project ..........
We could use FOSS analytics tools like OWA(https://www.openwebanalytics.com/) or something but yeah, I can see how Google Analytics makes things a lot easier.
Cool 👍
 I realize that at this point google has a monopoly over our internet and trying to use google alternatives is just nothing but a rabbit hole and a time sink which we do not want to get into .

**Comment by Bhupesh-V** [comment]
> > > Can we not have Google analytics on this website? It feels against the spirit of the internet. Do we really news that analytics? why do we Ned to connect everything to Google?
> > 
> > 
> > I feel ya, but we need it to see how far saadhan can reach. For those who don't like trackers one can always block it.
> 
> I understand that we need analytics but having a closed source analytics plugin on a FOSS Community project .......... We could use FOSS analytics tools like OWA(https://www.openwebanalytics.com/) or something but yeah, I can see how Google Analytics makes things a lot easier. Cool 👍 I realize that at this point google has a monopoly over our internet and trying to use google alternatives is just nothing but a rabbit hole and a time sink which we do not want to get into .

It's 2 faced, but that's the reality. I like what the folks at OWA doing, we have other tools like Fathom. But it all comes down to deploying/maintaining these ourselves, now since the managing team at devsindia is very small (and have full time jobs) we don't have the leverage to spent time doing that. Another thing is cost for deploying these self-hosted versions.
