### ISSUE TITLE
Using the new flask syntax

### ISSUE THREAD

**Issue by ghost** [developersIndia/saadhan#40]
### What happened?

Since the code uses Flask 2, we can replace `app.route` decorators with their corresponding `app.get`, `app.post` decorators to make the code much more readable and modern.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhupesh-V** [comment]
Sounds good to me, do you want to take this up @cynhash ?

Docs for reference: https://flask.palletsprojects.com/en/2.1.x/api/#flask.Flask.get

**Comment by cynhash** [comment]
Sure thing!
