### ISSUE TITLE
Saadhan resource fetch location is outdated 

### ISSUE THREAD

**Issue by Avii3301** [developersIndia/saadhan#48]
### What happened?

A to Z resource for [ML](https://saadhan.developersindia.in/resources?category=machine-learning) is leading to a dead page 
![image](https://github.com/developersIndia/saadhan/assets/63508047/efce3b1c-5d78-4b50-a3a7-161db98b678e)
**Open Link** leads to
![image](https://github.com/developersIndia/saadhan/assets/63508047/c9099598-5454-4dd0-b736-2dd70ccb801e)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by triach-rold** [comment]
Interesting.
It seems like a dead link. Fixing.

**Comment by triach-rold** [comment]
https://github.com/developersIndia/resources/pull/78 

PR to fix the issue.

**Comment by triach-rold** [comment]
For now, you can use [this](https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/ML/ML.md).

**Comment by Avii3301** [comment]
lol i can navigate a repo but thank you, gw
