### ISSUE TITLE
Add page for "How to contribute section"

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/saadhan#5]
### Feature details?

Design the HTML for this section with 2 ways to contribute:
- Contribute to resources
   - Here explain how users can contribute resources by sending PRs to the [resources repository](https://github.com/developersIndia/resources) (check readme for resources repo for some idea)
   - Go through the contribution guidelines for resources repo (you can choose to copy the guidelines directly) https://github.com/developersIndia/resources/blob/master/CONTRIBUTING.md
- Contribute to website
   - Link to saadhan's GitHub repo 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darshil-here** [comment]
Hey, I am interested in working on this issue (in fact I've started working on it). Please assign this issue to me.

**Comment by Bhupesh-V** [comment]
> Hey, I am interested in working on this issue (in fact I've started working on it). Please assign this issue to me.

Perfect!, if you have any doubts you can ask them here, if you have any design doubts, create a draft PR to get feedback!

**Comment by darshil-here** [comment]
Great! I've created a draft PR([here](https://github.com/developersIndia/saadhan/pull/24)), please take a look.

**Comment by darshil-here** [comment]
It seems I made some mistakes when I pushed code to my fork (synching my fork to the main branch), and now I'm having some problems understanding and solving the errors.

So I plan to delete the current fork and put together the webpage on my local machine, get your approval on the design, fork the main branch again, push it there, and then make the PR.

What are your thoughts on this?

cc: @Bhupesh-V

**Comment by Bhupesh-V** [comment]
> It seems I made some mistakes when I pushed code to my fork (synching my fork to the main branch), and now I'm having some problems understanding and solving the errors.
> 
> So I plan to delete the current fork and put together the webpage on my local machine, get your approval on the design, fork the main branch again, push it there, and then make the PR.
> 
> What are your thoughts on this?
> 
> cc: @Bhupesh-V

Sure no issues, by practice always make PRs from feature branches rather than from `main`. Take your time and create a fresh PR

**Comment by darshil-here** [comment]
## Description
Now, where do you want me to put the fork/star buttons on the webpage? (I've attached the screenshot, which I think is a pretty appropriate place to put those buttons) Also, which repository should I link to that fork/star button?

<img width="969" alt="image" src="https://user-images.githubusercontent.com/104206815/217835228-3d8e65e6-a483-4105-a106-4447df60a0a0.png">

## Checklist
- [x] The UI seems out of place right now, make sure to use appropriate bulma container classes (I am guessing it's a WIP)
- [ ] Can we add buttons for fork/star at appropriate place? Ref https://buttons.github.io/. Need to tell user where exactly the resources repository is.
- [x] Add another main heading to contribute to the saadhan website itself
- [x] Make sure to inherit base template, (see other pages)

## Screenshot (current status of website)
![screencapture-127-0-0-1-5500-templates-how-to-contribute-html-2023-02-09-19_19_04](https://user-images.githubusercontent.com/104206815/217830935-49b47697-79b7-482b-98f4-90c28ec08d12.png)

**Comment by Bhupesh-V** [comment]
This looks great 🔥 
Yes, I think we can add the star and fork button on the left side of main heading.

You can link the following repository https://github.com/developersIndia/resources

Let's do this
- Let's have 2 main headings
  1. `Contribute to developersIndia resources` `<star button> <fork button>`
      - this has all the details you have shown already
      - Use the following link for star and fork buttons https://github.com/developersIndia/resources
  3. `Contribute to saadhan website` `<star button> <fork button>`
       - Here we can just add a single paragraph with following content
         ```
          The website is built using Flask as backend and [HTMX](https://htmx.org/) with [Bulma](https://bulma.io) as frontend.
         ```
      - Use this repo's URL for stark and fork button
