### ISSUE TITLE
Add reviews section in each resource link

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/saadhan#7]
### Feature details?

Currently, the resource link doesn't show user reviews, even if they are returned from the API endpoint https://developersindia.github.io/resources/dsa/

It would be nice to show user reviews as a list etc if the JSON key is present. Show it above the "Open Link/Tweet section"

<img width="993" alt="Screenshot 2023-02-06 at 4 14 20 PM" src="https://user-images.githubusercontent.com/34342551/216952173-5e87a78a-f43a-420c-89d8-a6cd674febd0.png">

 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitBansal321** [comment]
if this issue still open i will work on it

**Comment by Bhupesh-V** [comment]
> if this issue still open i will work on it

Sure, go ahead, LMK if you need any help, if you have any design doubts, create a draft PR to get feedback. All the best!

**Comment by MohitBansal321** [comment]
but some of else added it

**Comment by Bhupesh-V** [comment]
> but some of else added it

You can still go ahead with the work, since this was assigned to you first, priority will be given to your PR

**Comment by MohitBansal321** [comment]
> > but some of else added it
> 
> You can still go ahead with the work, since this was assigned to you first, priority will be given to your PR

Thank you I will work on it

**Comment by MohitBansal321** [comment]
I have done my work  @Bhupesh-V 
now open for valuable feedback
Thank you
